callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    filename: checkpoint_{epoch:02d}
    monitor: val_loss
    save_last: True
    verbose: True
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_loss
    patience: 10
    verbose: True