defaults:
  - model_cfg: DenseNet
  - loggers@trainer_cfg: Default
  - callbacks@trainer_cfg: Default
  - override hydra/launcher: submitit_slurm
  #- override hydra/sweeper: ax

experiment_id: test_iris

hydra:
  run:
    dir: ./results/test/${experiment_id}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: ${hydra.run.dir}

  launcher:
    partition: gaia
    nodes: ${trainer_cfg.num_nodes}
    tasks_per_node: ${trainer_cfg.gpus}
    constraint: xeon-g6
    timeout_min: 1000000
    additional_parameters:
      gres: gpu:volta:2
      exclusive: True

data_cfg:
  datamodule:
    _target_: src.datasets.IrisDataModule
    batch_size: 32
    shuffle: True

trainer_cfg:
  _target_: pytorch_lightning.Trainer
  num_nodes: 1
  gpus: 1
  accelerator: ddp
  precision: 16
  max_epochs: 10